//
//  LoginHomeViewControllerInterfaces.swift
//  modularizationLoginProject
//
//  Created by Renan Alves on 31/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol LoginHomeViewControllerWireframeInterface: WireframeInterface {
}

protocol LoginHomeViewControllerViewInterface: ViewInterface {
}

protocol LoginHomeViewControllerPresenterInterface: PresenterInterface {
}

protocol LoginHomeViewControllerInteractorInterface: InteractorInterface {
}
