//
//  LoginHomeViewControllerPresenter.swift
//  modularizationLoginProject
//
//  Created by Renan Alves on 31/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

final class LoginHomeViewControllerPresenter {

    // MARK: - Private properties -

    private unowned let view: LoginHomeViewControllerViewInterface
    private let interactor: LoginHomeViewControllerInteractorInterface
    private let wireframe: LoginHomeViewControllerWireframeInterface
    
    // MARK: - Lifecycle -

    init(
        view: LoginHomeViewControllerViewInterface,
        interactor: LoginHomeViewControllerInteractorInterface,
        wireframe: LoginHomeViewControllerWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension LoginHomeViewControllerPresenter: LoginHomeViewControllerPresenterInterface {
}
