//
//  LoginHomeViewControllerWireframe.swift
//  modularizationLoginProject
//
//  Created by Renan Alves on 31/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginHomeViewControllerWireframe: BaseWireframe {

    // MARK: - Private properties -

    private var completion: (Bool) -> Void?
    private var controller: UINavigationController?
    
    // MARK: - Module setup -

    init(on navigationController: UINavigationController, _ completion: @escaping (Bool) -> Void) {
        let moduleViewController = LoginHomeViewControllerViewController()
        self.controller = navigationController
        self.completion = completion
        
        super.init(viewController: moduleViewController)

        let interactor = LoginHomeViewControllerInteractor()
        let presenter = LoginHomeViewControllerPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension LoginHomeViewControllerWireframe: LoginHomeViewControllerWireframeInterface {
    
}
