//
//  LoginHomeViewControllerInteractor.swift
//  modularizationLoginProject
//
//  Created by Renan Alves on 31/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class LoginHomeViewControllerInteractor {
}

// MARK: - Extensions -

extension LoginHomeViewControllerInteractor: LoginHomeViewControllerInteractorInterface {
}
