//
//  LoginHomeViewControllerViewController.swift
//  modularizationLoginProject
//
//  Created by Renan Alves on 31/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginHomeViewControllerViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: LoginHomeViewControllerPresenterInterface!

    private let label: UILabel = {
        let label = UILabel()
        label.text = "Hellow World"
        
        return label
    }()
    
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupHierarchyView()
        setupConstraints()
    }

    private func setupHierarchyView() {
        self.view.addSubview(label)
    }
    
    private func setupConstraints() {
        let centerX = NSLayoutConstraint(item: label, attribute: .centerX, relatedBy: .equal, toItem: self, attribute: .centerX, multiplier: 1, constant: 0)
        let centerY = NSLayoutConstraint(item: label, attribute: .centerY, relatedBy: .equal, toItem: self, attribute: .centerY, multiplier: 1, constant: 0)
        
        label.addConstraints([centerY, centerX])
    }
}

// MARK: - Extensions -

extension LoginHomeViewControllerViewController: LoginHomeViewControllerViewInterface {
}
